Jh/modulecard tags
ius-csg/cslabs-webapp pull request #74
Opened 2021-10-22 00:28 UTC by jhenry09

This is a draft for the tags section on module cards. the my modules and explore page were tested. Let me know about the style. 
![unknown](https://user-images.githubusercontent.com/77764403/138374593-ba4b409b-67c8-420c-a49c-c575f756a1ed.png)

2021-10-22 06:32 UTC, Cliftonz commented
I think this is good but I think would should make some changes.

I think that the tags should have 3 states instead of two.
The first is compressed similar to how Trello works with their tags. Only small bubbles no words.
![SmartSelect_20211022-022053_Trello.jpg](https://user-images.githubusercontent.com/43915749/138403846-60860523-45dd-4363-882c-faaa18bc5c77.jpg)
The second is open like you have currently where you see the bubble and the word. However, I think the expansion button should be a ... After the last tag instead of a big eye catchy arrow.
The last is expanded just like you have now where you can see all the tags. I do think the arrow on the top right should be replaced with an X.

The last detail is make sure you test this with a module that has no tags.

2021-10-22 06:36 UTC, Cliftonz commented
Also, how did you get to adding 25,000 lines of code?

I did you merge this branch with another?

2021-10-22 12:10 UTC, jhenry09 commented
> I think this is good but I think would should make some changes.
> 
> I think that the tags should have 3 states instead of two. The first is compressed similar to how Trello works with their tags. Only small bubbles no words. ![SmartSelect_20211022-022053_Trello.jpg](https://user-images.githubusercontent.com/43915749/138403846-60860523-45dd-4363-882c-faaa18bc5c77.jpg) The second is open like you have currently where you see the bubble and the word. However, I think the expansion button should be a ... After the last tag instead of a big eye catchy arrow. The last is expanded just like you have now where you can see all the tags. I do think the arrow on the top right should be replaced with an X.
> 
> The last detail is make sure you test this with a module that has no tags.

Got it. I will make these changes.

2021-10-22 12:11 UTC, jhenry09 commented
> Also, how did you get to adding 25,000 lines of code?
> 
> I did you merge this branch with another?

I did merge this with my tag editor branch but I am not sure why package-lock.json had 24k additions. Let me take a look at this when I get home this afternoon.

2021-10-22 13:52 UTC, Cliftonz commented
> 
> 
> > Also, how did you get to adding 25,000 lines of code?
> > I did you merge this branch with another?
> 
> I did merge this with my tag editor branch but I am not sure why package-lock.json had 24k additions. Let me take a look at this when I get home this afternoon.

Make sure that you merge the editor in first so you do not get merge conflicts.

2021-12-28 02:31 UTC, jasekiw commented
@jhenry09 Can you resolve the merge conflicts in this branch? Somehow you have merge conflicts with yourself

2022-01-10 23:50 UTC, jhenry09 commented
![435_gif2](https://user-images.githubusercontent.com/77764403/148857220-ba9b2f86-cead-4dd4-876a-d0b22ef9ccc1.gif)
Updated styling

2022-01-10 23:55 UTC, Cliftonz commented
discription text should be smaller and grey

2022-01-11 00:29 UTC, jhenry09 commented
> discription text should be smaller and grey

![image](https://user-images.githubusercontent.com/77764403/148860454-b68ab0f7-79cc-4909-a4de-0fd50e889411.png)
better?

2022-02-22 00:44 UTC, jasekiw requested changes

2022-02-22 00:44 UTC, jasekiw commented on src/components/ModuleCard/ModuleCard.tsx
> +}
this probably would be better located in the `util/index.ts` file

2022-02-22 00:44 UTC, jasekiw commented on src/pages/PublicModule/PublicModule.tsx
> +function doNothing() {
reuse the same doNothing method that you will move to the util folder.

2022-02-22 00:44 UTC, jasekiw commented on src/components/TagEditor/TagEditor.tsx
> +    else if (mes === 'display-only')
No need to have useEffect here, just assign the className directly.

2022-02-22 00:44 UTC, jasekiw commented on src/components/ModuleCard/ModuleCard.tsx
> +          {/*<Card.Img variant='top' src={TestImage}/>*/}
Remove this commented out code

2022-04-10 16:25 UTC, merged